# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hazzik's blog
tagline:          ''
description:      ''
url:              http://alexzaytsev.me
timezone:         'NZS-12:00'
tag_page_layout: tag_page
tag_page_dir: tag

author:
  name:           'Alexander Zaytsev'
  url:            http://alexzaytsev.me

paginate:         5

github:
  source:    'http://github.com/hazzik/alexzaytsev.me/edit/master/'

ya_metrika_id:    25093751

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
